# Site settings
title: "Arvind Radhakrishnen"
email: "arvindrkrishnen@gmail.com"
description: "Doxy is a responsive Jekyll template for your documentation or knowledgebase website"
keywords: "jekyll, minimal jekyll, jekyll theme, responsive jekyll, seo friendly blog, super fast blog, responsive"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://arvindrkrishnen.github.io"
cover_image: "https://themeix.com/wp-content/uploads/dooxy-responsive-html-template-preview.png" # Image will Display in Social Media When share the website
#facebook: "https://www.facebook.com"
twitter: "https://www.twitter.com/arvindrkrishnen"
#instagram: "https://www.instagram.com"
#github: "https://www.github.com"
linkedin: "https://www.linkedin.com/mwlite/in/arvindradhakrishnen"
#behance: "https://www.behance.com"
#reddit: "https://www.reddit.com"
#vimeo: "https://www.vimeo.com"
#dribble: "https://www.dribble.com"
#youtube: "https://www.youtube.com"

## Theme Options
animated_header: ""  #true 
twitter_username: arvindrkrishnen
github_username:  arvindrkrishnen


# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-archives
  - jekyll-seo-tag  
  - jekyll-sitemap
  - github-pages

collections:
  team_members:
    output: true
    permalink: /team_members/:path/
  testimonials:
    output: true
    permalink: /testimonials/:path/
  docs:
    output: true
    permalink: /docs/:title/
  posts:
    output: true
    permalink: "/blog/:slug"

paginate: 2
paginate_path: "/page:num/"

autopages:
  enabled: true
  collections:
    layouts: 
      - 'tag_page.html'
    title: ' :coll' # :coll is replaced by the collection name
    permalink: '/:coll/'
  
  tags:
    layouts: 
      - 'tag_page.html'
    title: ':tag' # :tag is replaced by the tag name
    permalink: '/tag/:tag'  
      

# Tag Options
tag_page_layout: tag_page
tag_page_dir: tag
permalink: /:title/ 

feed:
  collections:
    posts:
      path: "/index.xml"
